### PR TITLE
Fixes/Enhancements/Code reduction

### PR DESCRIPTION
**Pull request by cstansbury**
This is an overhaul of the existing implementation that is both backwards-compatible and accomplishes the following:
* added the ability to both clear and set the value of the rating input via exposed functionality
* fixed the incompatibility with fastclick
* follows the coding style used by standard bootstrap widgets (and in the process, reduces the minified code by ~600 bytes).

### CODE REVIEW

**Comment by cstansbury** [comment]
Looks like you've abandoned this project. Closing pull request.

**Comment by javiertoledo** [comment]
That are great changes, almost a rewrite that well deserve that 3.x version bump, I’d be glad to merge your changes. It’s also true that I haven’t paid too much attention to this project lately, so you’re welcome if you or someone else wants to maintain it :-)

**Comment by cstansbury** [comment]
Thanks @javiertoledo. It now does everything I need it to do... so I probably won't be revisiting it for a while. If, however, you ever need help with it's maintenance, please don't hesitate to ping me for some assistance.

PS - There might be one or more outstanding issues (like the fastclick-related issue) that you can close now.

**Comment by javiertoledo** [comment]
Thanks again for your help!

**Pull request merged**
